# Generated by Django 4.2 on 2023-11-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SaveEnquery',
            new_name='FormSubmit',
        ),
    ]
